{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kotlinforforge",
    "version": "5.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "5.7.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "thedarkcolour",
          "module": "kfflang",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kfflib",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kffmod",
          "version": {
            "requires": "5.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinforforge-5.7.0-all.jar",
          "url": "kotlinforforge-5.7.0-all.jar",
          "size": 6205418,
          "sha512": "9cb875fa67dba57aa4e1b19dc5363820f5d5394e85360aecd1fb56f122567a06940f2214b4e2ce55f8571bb039cfc0eb5964aeccb3c2b67c4f0c852b940c0c39",
          "sha256": "710760d6e0386a2ce8a4dbe42aa2d9621274019663c3dc8316a735d271ce4c60",
          "sha1": "c0304db19e5d98db399af537c6fb04d6e1836826",
          "md5": "f40cd2d0670b897e4ef916e62fbc16db"
        }
      ]
    }
  ]
}
