{
  "formatVersion": "1.1",
  "component": {
    "group": "thedarkcolour",
    "module": "kfflang",
    "version": "5.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "kfflang-5.6.0.jar",
          "url": "kfflang-5.6.0.jar",
          "size": 23472,
          "sha512": "99e2e34c2caf55a4fdbc6f2fffb3f39ca4419bca10680e5469e09c83eb89a4e7ebb0d4f66a68cbc9789f304c25acb68226e595edded23315bc6645cf405e79ea",
          "sha256": "e8d28daf937f69ceebb6893565233859c057da6086b5070422e60bb9c4add6ce",
          "sha1": "95ea9a35d1fa3f39df3a9503a4ff9859d36e8919",
          "md5": "b8a990e11bc88b00c67a6d7e91e8f412"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kfflang-5.6.0.jar",
          "url": "kfflang-5.6.0.jar",
          "size": 23472,
          "sha512": "99e2e34c2caf55a4fdbc6f2fffb3f39ca4419bca10680e5469e09c83eb89a4e7ebb0d4f66a68cbc9789f304c25acb68226e595edded23315bc6645cf405e79ea",
          "sha256": "e8d28daf937f69ceebb6893565233859c057da6086b5070422e60bb9c4add6ce",
          "sha1": "95ea9a35d1fa3f39df3a9503a4ff9859d36e8919",
          "md5": "b8a990e11bc88b00c67a6d7e91e8f412"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kfflang-5.6.0-sources.jar",
          "url": "kfflang-5.6.0-sources.jar",
          "size": 7441,
          "sha512": "6832d400b4b67c8218040e912c8265a8a83fe5a641ea16cd6589d2920ccbc0388a061aeb56c15f8935c6d526eb61a22677cfd3cb3106d3aab11bf9feb8159476",
          "sha256": "bf26c692d6e7b86b62ba91a3616be2e50553f013986cd6e6d94630e29915d06a",
          "sha1": "b548f263dee7fcad1dc7fc04a4f85a71183687db",
          "md5": "84e7dcde9921e899bc20e33fbb214da6"
        }
      ]
    }
  ]
}
